apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: distributed-chat-perker-ethen
  name: chat-db-deployment
  labels:
    app: db-svc # Changed to match the service selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-svc # Ensure the selector matches the pod label
  template:
    metadata:
      labels:
        app: db-svc # Changed to match the service selector
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432
          volumeMounts:
            # - mountPath: /var/lib/postgresql/data
            #   name: postgres-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: schema-volume
      volumes:
        # - name: postgres-storage
        #   persistentVolumeClaim:
        #     claimName: db-pvc
        - name: schema-volume
          configMap:
            name: db-init
