apiVersion: v1
kind: Service
metadata:
  namespace: distributed-chat-perker-ethen
  name: db-svc
  labels:
    app: db-svc
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db-svc
