apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: distributed-chat-perker-ethen
  name: image1-pvc
  labels:
    app: chat-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi