name: Build and deploy on kubernetes
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -f Api/Dockerfile \
            -t alexmickelson/distributed-chat-api:${{ github.run_number }} \
            -t alexmickelson/distributed-chat-api:latest \
            .
          
          docker push alexmickelson/distributed-chat-api --all-tags

          docker build \
            -f Client/Dockerfile \
            -t alexmickelson/distributed-chat-client:${{ github.run_number }} \
            -t alexmickelson/distributed-chat-client:latest \
            .
          
          docker push alexmickelson/distributed-chat-client --all-tags

      - name: Deploy to Kubernetes
        run: |
          export PATH=$PATH:~/.nix-profile/bin:/nix/var/nix/profiles/default/bin

          export IMAGE_TAG=${{ github.run_number }}

          kubectl -n distributed-chat-alex delete configmap db-init || true
          kubectl -n distributed-chat-alex create configmap db-init --from-file=init.sql

          for file in kube/*; do 
              cat "$file" | envsubst | kubectl apply -f -; 
          done
